# Generated by Django 3.1.3 on 2020-12-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='user_name')),
                ('fname', models.CharField(max_length=60, verbose_name='father_name')),
                ('email', models.TextField(verbose_name='email_adress')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
        ),
    ]
