# Generated by Django 3.1.4 on 2020-12-29 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adrress',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=60, verbose_name='fathername'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60, verbose_name='username'),
        ),
    ]
