# Generated by Django 3.1.4 on 2020-12-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20201229_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
