# Generated by Django 3.1.3 on 2020-12-06 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('tittle', models.CharField(max_length=200, verbose_name='post tittle')),
                ('post', models.TextField(verbose_name='Post')),
                ('post_date', models.DateField(default=datetime.datetime(2020, 12, 6, 19, 40, 56, 272701, tzinfo=utc))),
                ('good_name', models.CharField(max_length=50, verbose_name='Good name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_user')),
            ],
        ),
    ]
