# Generated by Django 3.1.3 on 2020-12-06 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 19, 44, 56, 935983, tzinfo=utc)),
        ),
    ]
