# Generated by Django 3.1.3 on 2020-12-06 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201207_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 47, 2, 802269, tzinfo=utc)),
        ),
    ]
