# Generated by Django 3.1.3 on 2020-12-06 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201207_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
