# Generated by Django 3.1.3 on 2020-12-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201207_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blog_User',
        ),
    ]
