# Generated by Django 3.1.3 on 2020-12-06 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0007_auto_20201207_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='User name')),
                ('email', models.CharField(max_length=100, verbose_name='User email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('tittle', models.CharField(max_length=200, verbose_name='post tittle')),
                ('post', models.TextField(verbose_name='Post')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('good_name', models.CharField(max_length=50, verbose_name='Good name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_user')),
            ],
        ),
    ]
